// Code generated by ent, DO NOT EDIT.

package thinghttp

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the thinghttp type in the database.
	Label = "thing_http"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeProbesHTTP holds the string denoting the probes_http edge name in mutations.
	EdgeProbesHTTP = "probes_http"
	// Table holds the table name of the thinghttp in the database.
	Table = "thing_htt_ps"
	// ProbesHTTPTable is the table that holds the probes_http relation/edge. The primary key declared below.
	ProbesHTTPTable = "thing_http_probes_http"
	// ProbesHTTPInverseTable is the table name for the Thing entity.
	// It exists in this package in order to avoid circular dependency with the "thing" package.
	ProbesHTTPInverseTable = "things"
)

// Columns holds all SQL columns for thinghttp fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldName,
}

var (
	// ProbesHTTPPrimaryKey and ProbesHTTPColumn2 are the table columns denoting the
	// primary key for the probes_http relation (M2M).
	ProbesHTTPPrimaryKey = []string{"thing_http_id", "thing_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ThingHTTP queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAge orders the results by the age field.
func ByAge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAge, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProbesHTTPCount orders the results by probes_http count.
func ByProbesHTTPCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProbesHTTPStep(), opts...)
	}
}

// ByProbesHTTP orders the results by probes_http terms.
func ByProbesHTTP(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProbesHTTPStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProbesHTTPStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProbesHTTPInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ProbesHTTPTable, ProbesHTTPPrimaryKey...),
	)
}
