// Code generated by ent, DO NOT EDIT.

package thinghttp

import (
	"entgo.io/bug/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLTE(FieldID, id))
}

// Age applies equality check predicate on the "age" field. It's identical to AgeEQ.
func Age(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldAge, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldName, v))
}

// AgeEQ applies the EQ predicate on the "age" field.
func AgeEQ(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldAge, v))
}

// AgeNEQ applies the NEQ predicate on the "age" field.
func AgeNEQ(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNEQ(FieldAge, v))
}

// AgeIn applies the In predicate on the "age" field.
func AgeIn(vs ...int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldIn(FieldAge, vs...))
}

// AgeNotIn applies the NotIn predicate on the "age" field.
func AgeNotIn(vs ...int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNotIn(FieldAge, vs...))
}

// AgeGT applies the GT predicate on the "age" field.
func AgeGT(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGT(FieldAge, v))
}

// AgeGTE applies the GTE predicate on the "age" field.
func AgeGTE(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGTE(FieldAge, v))
}

// AgeLT applies the LT predicate on the "age" field.
func AgeLT(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLT(FieldAge, v))
}

// AgeLTE applies the LTE predicate on the "age" field.
func AgeLTE(v int) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLTE(FieldAge, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.FieldContainsFold(FieldName, v))
}

// HasProbesHTTP applies the HasEdge predicate on the "probes_http" edge.
func HasProbesHTTP() predicate.ThingHTTP {
	return predicate.ThingHTTP(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ProbesHTTPTable, ProbesHTTPPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProbesHTTPWith applies the HasEdge predicate on the "probes_http" edge with a given conditions (other predicates).
func HasProbesHTTPWith(preds ...predicate.Thing) predicate.ThingHTTP {
	return predicate.ThingHTTP(func(s *sql.Selector) {
		step := newProbesHTTPStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ThingHTTP) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ThingHTTP) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ThingHTTP) predicate.ThingHTTP {
	return predicate.ThingHTTP(sql.NotPredicates(p))
}
