// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateThingHTTPRes interface {
	createThingHTTPRes()
}

type CreateThingRes interface {
	createThingRes()
}

type DeleteThingHTTPRes interface {
	deleteThingHTTPRes()
}

type DeleteThingRes interface {
	deleteThingRes()
}

type ListThingHTTPProbesHttpRes interface {
	listThingHTTPProbesHttpRes()
}

type ListThingHTTPRes interface {
	listThingHTTPRes()
}

type ListThingProbedByRes interface {
	listThingProbedByRes()
}

type ListThingRes interface {
	listThingRes()
}

type ReadThingHTTPRes interface {
	readThingHTTPRes()
}

type ReadThingRes interface {
	readThingRes()
}

type UpdateThingHTTPRes interface {
	updateThingHTTPRes()
}

type UpdateThingRes interface {
	updateThingRes()
}
