// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/errors"
)

func (s ListThingHTTPOKApplicationJSON) Validate() error {
	alias := ([]ThingHTTPList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListThingHTTPProbesHttpOKApplicationJSON) Validate() error {
	alias := ([]ThingHTTPProbesHTTPList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListThingOKApplicationJSON) Validate() error {
	alias := ([]ThingList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListThingProbedByOKApplicationJSON) Validate() error {
	alias := ([]ThingProbedByList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
