// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateThing implements createThing operation.
//
// Creates a new Thing and persists it to storage.
//
// POST /things
func (UnimplementedHandler) CreateThing(ctx context.Context, req *CreateThingReq) (r CreateThingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateThingHTTP implements createThingHTTP operation.
//
// Creates a new ThingHTTP and persists it to storage.
//
// POST /thing-https
func (UnimplementedHandler) CreateThingHTTP(ctx context.Context, req *CreateThingHTTPReq) (r CreateThingHTTPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteThing implements deleteThing operation.
//
// Deletes the Thing with the requested ID.
//
// DELETE /things/{id}
func (UnimplementedHandler) DeleteThing(ctx context.Context, params DeleteThingParams) (r DeleteThingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteThingHTTP implements deleteThingHTTP operation.
//
// Deletes the ThingHTTP with the requested ID.
//
// DELETE /thing-https/{id}
func (UnimplementedHandler) DeleteThingHTTP(ctx context.Context, params DeleteThingHTTPParams) (r DeleteThingHTTPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListThing implements listThing operation.
//
// List Things.
//
// GET /things
func (UnimplementedHandler) ListThing(ctx context.Context, params ListThingParams) (r ListThingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListThingHTTP implements listThingHTTP operation.
//
// List ThingHTTPs.
//
// GET /thing-https
func (UnimplementedHandler) ListThingHTTP(ctx context.Context, params ListThingHTTPParams) (r ListThingHTTPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListThingHTTPProbesHttp implements listThingHTTPProbesHttp operation.
//
// List attached ProbesHttps.
//
// GET /thing-https/{id}/probes-http
func (UnimplementedHandler) ListThingHTTPProbesHttp(ctx context.Context, params ListThingHTTPProbesHttpParams) (r ListThingHTTPProbesHttpRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListThingProbedBy implements listThingProbedBy operation.
//
// List attached ProbedBys.
//
// GET /things/{id}/probed-by
func (UnimplementedHandler) ListThingProbedBy(ctx context.Context, params ListThingProbedByParams) (r ListThingProbedByRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadThing implements readThing operation.
//
// Finds the Thing with the requested ID and returns it.
//
// GET /things/{id}
func (UnimplementedHandler) ReadThing(ctx context.Context, params ReadThingParams) (r ReadThingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadThingHTTP implements readThingHTTP operation.
//
// Finds the ThingHTTP with the requested ID and returns it.
//
// GET /thing-https/{id}
func (UnimplementedHandler) ReadThingHTTP(ctx context.Context, params ReadThingHTTPParams) (r ReadThingHTTPRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateThing implements updateThing operation.
//
// Updates a Thing and persists changes to storage.
//
// PATCH /things/{id}
func (UnimplementedHandler) UpdateThing(ctx context.Context, req *UpdateThingReq, params UpdateThingParams) (r UpdateThingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateThingHTTP implements updateThingHTTP operation.
//
// Updates a ThingHTTP and persists changes to storage.
//
// PATCH /thing-https/{id}
func (UnimplementedHandler) UpdateThingHTTP(ctx context.Context, req *UpdateThingHTTPReq, params UpdateThingHTTPParams) (r UpdateThingHTTPRes, _ error) {
	return r, ht.ErrNotImplemented
}
