// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateThing implements createThing operation.
	//
	// Creates a new Thing and persists it to storage.
	//
	// POST /things
	CreateThing(ctx context.Context, req *CreateThingReq) (CreateThingRes, error)
	// CreateThingHTTP implements createThingHTTP operation.
	//
	// Creates a new ThingHTTP and persists it to storage.
	//
	// POST /thing-https
	CreateThingHTTP(ctx context.Context, req *CreateThingHTTPReq) (CreateThingHTTPRes, error)
	// DeleteThing implements deleteThing operation.
	//
	// Deletes the Thing with the requested ID.
	//
	// DELETE /things/{id}
	DeleteThing(ctx context.Context, params DeleteThingParams) (DeleteThingRes, error)
	// DeleteThingHTTP implements deleteThingHTTP operation.
	//
	// Deletes the ThingHTTP with the requested ID.
	//
	// DELETE /thing-https/{id}
	DeleteThingHTTP(ctx context.Context, params DeleteThingHTTPParams) (DeleteThingHTTPRes, error)
	// ListThing implements listThing operation.
	//
	// List Things.
	//
	// GET /things
	ListThing(ctx context.Context, params ListThingParams) (ListThingRes, error)
	// ListThingHTTP implements listThingHTTP operation.
	//
	// List ThingHTTPs.
	//
	// GET /thing-https
	ListThingHTTP(ctx context.Context, params ListThingHTTPParams) (ListThingHTTPRes, error)
	// ListThingHTTPProbesHttp implements listThingHTTPProbesHttp operation.
	//
	// List attached ProbesHttps.
	//
	// GET /thing-https/{id}/probes-http
	ListThingHTTPProbesHttp(ctx context.Context, params ListThingHTTPProbesHttpParams) (ListThingHTTPProbesHttpRes, error)
	// ListThingProbedBy implements listThingProbedBy operation.
	//
	// List attached ProbedBys.
	//
	// GET /things/{id}/probed-by
	ListThingProbedBy(ctx context.Context, params ListThingProbedByParams) (ListThingProbedByRes, error)
	// ReadThing implements readThing operation.
	//
	// Finds the Thing with the requested ID and returns it.
	//
	// GET /things/{id}
	ReadThing(ctx context.Context, params ReadThingParams) (ReadThingRes, error)
	// ReadThingHTTP implements readThingHTTP operation.
	//
	// Finds the ThingHTTP with the requested ID and returns it.
	//
	// GET /thing-https/{id}
	ReadThingHTTP(ctx context.Context, params ReadThingHTTPParams) (ReadThingHTTPRes, error)
	// UpdateThing implements updateThing operation.
	//
	// Updates a Thing and persists changes to storage.
	//
	// PATCH /things/{id}
	UpdateThing(ctx context.Context, req *UpdateThingReq, params UpdateThingParams) (UpdateThingRes, error)
	// UpdateThingHTTP implements updateThingHTTP operation.
	//
	// Updates a ThingHTTP and persists changes to storage.
	//
	// PATCH /thing-https/{id}
	UpdateThingHTTP(ctx context.Context, req *UpdateThingHTTPReq, params UpdateThingHTTPParams) (UpdateThingHTTPRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
