// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/thing"
	"entgo.io/bug/ent/thinghttp"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThingHTTPQuery is the builder for querying ThingHTTP entities.
type ThingHTTPQuery struct {
	config
	ctx            *QueryContext
	order          []thinghttp.OrderOption
	inters         []Interceptor
	predicates     []predicate.ThingHTTP
	withProbesHTTP *ThingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ThingHTTPQuery builder.
func (thq *ThingHTTPQuery) Where(ps ...predicate.ThingHTTP) *ThingHTTPQuery {
	thq.predicates = append(thq.predicates, ps...)
	return thq
}

// Limit the number of records to be returned by this query.
func (thq *ThingHTTPQuery) Limit(limit int) *ThingHTTPQuery {
	thq.ctx.Limit = &limit
	return thq
}

// Offset to start from.
func (thq *ThingHTTPQuery) Offset(offset int) *ThingHTTPQuery {
	thq.ctx.Offset = &offset
	return thq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (thq *ThingHTTPQuery) Unique(unique bool) *ThingHTTPQuery {
	thq.ctx.Unique = &unique
	return thq
}

// Order specifies how the records should be ordered.
func (thq *ThingHTTPQuery) Order(o ...thinghttp.OrderOption) *ThingHTTPQuery {
	thq.order = append(thq.order, o...)
	return thq
}

// QueryProbesHTTP chains the current query on the "probes_http" edge.
func (thq *ThingHTTPQuery) QueryProbesHTTP() *ThingQuery {
	query := (&ThingClient{config: thq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := thq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := thq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(thinghttp.Table, thinghttp.FieldID, selector),
			sqlgraph.To(thing.Table, thing.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, thinghttp.ProbesHTTPTable, thinghttp.ProbesHTTPPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(thq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ThingHTTP entity from the query.
// Returns a *NotFoundError when no ThingHTTP was found.
func (thq *ThingHTTPQuery) First(ctx context.Context) (*ThingHTTP, error) {
	nodes, err := thq.Limit(1).All(setContextOp(ctx, thq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{thinghttp.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (thq *ThingHTTPQuery) FirstX(ctx context.Context) *ThingHTTP {
	node, err := thq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ThingHTTP ID from the query.
// Returns a *NotFoundError when no ThingHTTP ID was found.
func (thq *ThingHTTPQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(1).IDs(setContextOp(ctx, thq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{thinghttp.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (thq *ThingHTTPQuery) FirstIDX(ctx context.Context) int {
	id, err := thq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ThingHTTP entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ThingHTTP entity is found.
// Returns a *NotFoundError when no ThingHTTP entities are found.
func (thq *ThingHTTPQuery) Only(ctx context.Context) (*ThingHTTP, error) {
	nodes, err := thq.Limit(2).All(setContextOp(ctx, thq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{thinghttp.Label}
	default:
		return nil, &NotSingularError{thinghttp.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (thq *ThingHTTPQuery) OnlyX(ctx context.Context) *ThingHTTP {
	node, err := thq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ThingHTTP ID in the query.
// Returns a *NotSingularError when more than one ThingHTTP ID is found.
// Returns a *NotFoundError when no entities are found.
func (thq *ThingHTTPQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = thq.Limit(2).IDs(setContextOp(ctx, thq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{thinghttp.Label}
	default:
		err = &NotSingularError{thinghttp.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (thq *ThingHTTPQuery) OnlyIDX(ctx context.Context) int {
	id, err := thq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ThingHTTPs.
func (thq *ThingHTTPQuery) All(ctx context.Context) ([]*ThingHTTP, error) {
	ctx = setContextOp(ctx, thq.ctx, "All")
	if err := thq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ThingHTTP, *ThingHTTPQuery]()
	return withInterceptors[[]*ThingHTTP](ctx, thq, qr, thq.inters)
}

// AllX is like All, but panics if an error occurs.
func (thq *ThingHTTPQuery) AllX(ctx context.Context) []*ThingHTTP {
	nodes, err := thq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ThingHTTP IDs.
func (thq *ThingHTTPQuery) IDs(ctx context.Context) (ids []int, err error) {
	if thq.ctx.Unique == nil && thq.path != nil {
		thq.Unique(true)
	}
	ctx = setContextOp(ctx, thq.ctx, "IDs")
	if err = thq.Select(thinghttp.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (thq *ThingHTTPQuery) IDsX(ctx context.Context) []int {
	ids, err := thq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (thq *ThingHTTPQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, thq.ctx, "Count")
	if err := thq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, thq, querierCount[*ThingHTTPQuery](), thq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (thq *ThingHTTPQuery) CountX(ctx context.Context) int {
	count, err := thq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (thq *ThingHTTPQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, thq.ctx, "Exist")
	switch _, err := thq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (thq *ThingHTTPQuery) ExistX(ctx context.Context) bool {
	exist, err := thq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ThingHTTPQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (thq *ThingHTTPQuery) Clone() *ThingHTTPQuery {
	if thq == nil {
		return nil
	}
	return &ThingHTTPQuery{
		config:         thq.config,
		ctx:            thq.ctx.Clone(),
		order:          append([]thinghttp.OrderOption{}, thq.order...),
		inters:         append([]Interceptor{}, thq.inters...),
		predicates:     append([]predicate.ThingHTTP{}, thq.predicates...),
		withProbesHTTP: thq.withProbesHTTP.Clone(),
		// clone intermediate query.
		sql:  thq.sql.Clone(),
		path: thq.path,
	}
}

// WithProbesHTTP tells the query-builder to eager-load the nodes that are connected to
// the "probes_http" edge. The optional arguments are used to configure the query builder of the edge.
func (thq *ThingHTTPQuery) WithProbesHTTP(opts ...func(*ThingQuery)) *ThingHTTPQuery {
	query := (&ThingClient{config: thq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	thq.withProbesHTTP = query
	return thq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ThingHTTP.Query().
//		GroupBy(thinghttp.FieldAge).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (thq *ThingHTTPQuery) GroupBy(field string, fields ...string) *ThingHTTPGroupBy {
	thq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ThingHTTPGroupBy{build: thq}
	grbuild.flds = &thq.ctx.Fields
	grbuild.label = thinghttp.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Age int `json:"age,omitempty"`
//	}
//
//	client.ThingHTTP.Query().
//		Select(thinghttp.FieldAge).
//		Scan(ctx, &v)
func (thq *ThingHTTPQuery) Select(fields ...string) *ThingHTTPSelect {
	thq.ctx.Fields = append(thq.ctx.Fields, fields...)
	sbuild := &ThingHTTPSelect{ThingHTTPQuery: thq}
	sbuild.label = thinghttp.Label
	sbuild.flds, sbuild.scan = &thq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ThingHTTPSelect configured with the given aggregations.
func (thq *ThingHTTPQuery) Aggregate(fns ...AggregateFunc) *ThingHTTPSelect {
	return thq.Select().Aggregate(fns...)
}

func (thq *ThingHTTPQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range thq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, thq); err != nil {
				return err
			}
		}
	}
	for _, f := range thq.ctx.Fields {
		if !thinghttp.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if thq.path != nil {
		prev, err := thq.path(ctx)
		if err != nil {
			return err
		}
		thq.sql = prev
	}
	return nil
}

func (thq *ThingHTTPQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ThingHTTP, error) {
	var (
		nodes       = []*ThingHTTP{}
		_spec       = thq.querySpec()
		loadedTypes = [1]bool{
			thq.withProbesHTTP != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ThingHTTP).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ThingHTTP{config: thq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, thq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := thq.withProbesHTTP; query != nil {
		if err := thq.loadProbesHTTP(ctx, query, nodes,
			func(n *ThingHTTP) { n.Edges.ProbesHTTP = []*Thing{} },
			func(n *ThingHTTP, e *Thing) { n.Edges.ProbesHTTP = append(n.Edges.ProbesHTTP, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (thq *ThingHTTPQuery) loadProbesHTTP(ctx context.Context, query *ThingQuery, nodes []*ThingHTTP, init func(*ThingHTTP), assign func(*ThingHTTP, *Thing)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*ThingHTTP)
	nids := make(map[int]map[*ThingHTTP]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(thinghttp.ProbesHTTPTable)
		s.Join(joinT).On(s.C(thing.FieldID), joinT.C(thinghttp.ProbesHTTPPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(thinghttp.ProbesHTTPPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(thinghttp.ProbesHTTPPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*ThingHTTP]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Thing](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "probes_http" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (thq *ThingHTTPQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := thq.querySpec()
	_spec.Node.Columns = thq.ctx.Fields
	if len(thq.ctx.Fields) > 0 {
		_spec.Unique = thq.ctx.Unique != nil && *thq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, thq.driver, _spec)
}

func (thq *ThingHTTPQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(thinghttp.Table, thinghttp.Columns, sqlgraph.NewFieldSpec(thinghttp.FieldID, field.TypeInt))
	_spec.From = thq.sql
	if unique := thq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if thq.path != nil {
		_spec.Unique = true
	}
	if fields := thq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thinghttp.FieldID)
		for i := range fields {
			if fields[i] != thinghttp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := thq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := thq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := thq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := thq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (thq *ThingHTTPQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(thq.driver.Dialect())
	t1 := builder.Table(thinghttp.Table)
	columns := thq.ctx.Fields
	if len(columns) == 0 {
		columns = thinghttp.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if thq.sql != nil {
		selector = thq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if thq.ctx.Unique != nil && *thq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range thq.predicates {
		p(selector)
	}
	for _, p := range thq.order {
		p(selector)
	}
	if offset := thq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := thq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ThingHTTPGroupBy is the group-by builder for ThingHTTP entities.
type ThingHTTPGroupBy struct {
	selector
	build *ThingHTTPQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (thgb *ThingHTTPGroupBy) Aggregate(fns ...AggregateFunc) *ThingHTTPGroupBy {
	thgb.fns = append(thgb.fns, fns...)
	return thgb
}

// Scan applies the selector query and scans the result into the given value.
func (thgb *ThingHTTPGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, thgb.build.ctx, "GroupBy")
	if err := thgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ThingHTTPQuery, *ThingHTTPGroupBy](ctx, thgb.build, thgb, thgb.build.inters, v)
}

func (thgb *ThingHTTPGroupBy) sqlScan(ctx context.Context, root *ThingHTTPQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(thgb.fns))
	for _, fn := range thgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*thgb.flds)+len(thgb.fns))
		for _, f := range *thgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*thgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := thgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ThingHTTPSelect is the builder for selecting fields of ThingHTTP entities.
type ThingHTTPSelect struct {
	*ThingHTTPQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ths *ThingHTTPSelect) Aggregate(fns ...AggregateFunc) *ThingHTTPSelect {
	ths.fns = append(ths.fns, fns...)
	return ths
}

// Scan applies the selector query and scans the result into the given value.
func (ths *ThingHTTPSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ths.ctx, "Select")
	if err := ths.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ThingHTTPQuery, *ThingHTTPSelect](ctx, ths.ThingHTTPQuery, ths, ths.inters, v)
}

func (ths *ThingHTTPSelect) sqlScan(ctx context.Context, root *ThingHTTPQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ths.fns))
	for _, fn := range ths.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ths.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ths.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
