// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/bug/ent/predicate"
	"entgo.io/bug/ent/thinghttp"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThingHTTPDelete is the builder for deleting a ThingHTTP entity.
type ThingHTTPDelete struct {
	config
	hooks    []Hook
	mutation *ThingHTTPMutation
}

// Where appends a list predicates to the ThingHTTPDelete builder.
func (thd *ThingHTTPDelete) Where(ps ...predicate.ThingHTTP) *ThingHTTPDelete {
	thd.mutation.Where(ps...)
	return thd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (thd *ThingHTTPDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, thd.sqlExec, thd.mutation, thd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (thd *ThingHTTPDelete) ExecX(ctx context.Context) int {
	n, err := thd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (thd *ThingHTTPDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(thinghttp.Table, sqlgraph.NewFieldSpec(thinghttp.FieldID, field.TypeInt))
	if ps := thd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, thd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	thd.mutation.done = true
	return affected, err
}

// ThingHTTPDeleteOne is the builder for deleting a single ThingHTTP entity.
type ThingHTTPDeleteOne struct {
	thd *ThingHTTPDelete
}

// Where appends a list predicates to the ThingHTTPDelete builder.
func (thdo *ThingHTTPDeleteOne) Where(ps ...predicate.ThingHTTP) *ThingHTTPDeleteOne {
	thdo.thd.mutation.Where(ps...)
	return thdo
}

// Exec executes the deletion query.
func (thdo *ThingHTTPDeleteOne) Exec(ctx context.Context) error {
	n, err := thdo.thd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{thinghttp.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (thdo *ThingHTTPDeleteOne) ExecX(ctx context.Context) {
	if err := thdo.Exec(ctx); err != nil {
		panic(err)
	}
}
