// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/thing"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Thing is the model entity for the Thing schema.
type Thing struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Age holds the value of the "age" field.
	Age int `json:"age,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThingQuery when eager-loading is set.
	Edges        ThingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ThingEdges holds the relations/edges for other nodes in the graph.
type ThingEdges struct {
	// ProbedBy holds the value of the probed_by edge.
	ProbedBy []*ThingHTTP `json:"probed_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProbedByOrErr returns the ProbedBy value or an error if the edge
// was not loaded in eager-loading.
func (e ThingEdges) ProbedByOrErr() ([]*ThingHTTP, error) {
	if e.loadedTypes[0] {
		return e.ProbedBy, nil
	}
	return nil, &NotLoadedError{edge: "probed_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Thing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case thing.FieldID, thing.FieldAge:
			values[i] = new(sql.NullInt64)
		case thing.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Thing fields.
func (t *Thing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case thing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case thing.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				t.Age = int(value.Int64)
			}
		case thing.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				t.Name = value.String
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Thing.
// This includes values selected through modifiers, order, etc.
func (t *Thing) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryProbedBy queries the "probed_by" edge of the Thing entity.
func (t *Thing) QueryProbedBy() *ThingHTTPQuery {
	return NewThingClient(t.config).QueryProbedBy(t)
}

// Update returns a builder for updating this Thing.
// Note that you need to call Thing.Unwrap() before calling this method if this Thing
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Thing) Update() *ThingUpdateOne {
	return NewThingClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Thing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Thing) Unwrap() *Thing {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Thing is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Thing) String() string {
	var builder strings.Builder
	builder.WriteString("Thing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", t.Age))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(t.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Things is a parsable slice of Thing.
type Things []*Thing
