// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Thing is the predicate function for thing builders.
type Thing func(*sql.Selector)

// ThingHTTP is the predicate function for thinghttp builders.
type ThingHTTP func(*sql.Selector)
